### ISSUE TITLE
V58 Grundläggande Terminalkommandon

### ISSUE THREAD

**Issue by matilds** [IOOPM-UU/achievements#11]
"Ett år stötte jag (Tobias) på en student på kursen som hade blandat ihop ^C och ^Z och som därför hade 50+ instanser av lagerhanteraren igång eftersom han, varje gång han trodde att han slog ihjäl programmet med 

> ^C           // Ska vara ^Z? 

, bara hade pausat det."

**Comment by TobiasWrigstad** [comment]
Tack! Fixat!
