### ISSUE TITLE
H18 Saknas i auportal

### ISSUE THREAD

**Issue by novium** [IOOPM-UU/achievements#8]
H18 (Jämförelsemetoden equals) verkar saknas i portalen. [(länk till fil)](https://github.com/IOOPM-UU/achievements/blob/master/H18.md)

_(Crosspost i piazza)_

**Comment by antonohlsson8781** [comment]
Detta verkar fortfarande inte vara löst, auportalens mål 18 hänvisar istället till (det icke-existerande) målet G18: 

"G18 Resonera kring hur inkapsling både kan försvåra och underlätta testning (ta gärna hjälp av kodexempel)"

**Comment by novium** [comment]
Om det inte finns i auportalen så behöver du inte göra målet

**Comment by novium** [comment]
Update: Verkar som att det snarast har blivit lite fel i överföringen genom att målet G18 - "Resonera kring hur inkapsling både kan försvåra och underlätta testning (ta gärna hjälp av kodexempel)" nu saknar målbeskrivning och målet H18 (som inte fanns förra terminen) har kommit tillbaka.

Edit: Därför finns nu 2 stycken G17-mål (ett .md och ett .org) >> G18 har blivit till G17.org och H18 tillkommit
